# Generated by Django 4.0.4 on 2022-06-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_app', '0002_rename_name_dogs_dog_name_alter_dogs_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='e_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=64, verbose_name='Nazwa usługi'),
        ),
    ]
