# Generated by Django 4.0.4 on 2022-06-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_app', '0003_employees_e_mail_alter_service_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(verbose_name='Cena'),
        ),
    ]
