# Generated by Django 4.0.4 on 2022-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_app', '0004_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='breed',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='dogs',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='e_mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
    ]
