# Generated by Django 4.0.4 on 2022-06-08 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_app', '0007_alter_service_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='dog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='grooming_app.dogs'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='e_mail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
