# Generated by Django 4.0.4 on 2022-06-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_app', '0008_employees_dog_alter_employees_e_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='description',
            field=models.TextField(null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='e_mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(max_length=9, null=True, unique=True, verbose_name='Numer telefonu'),
        ),
    ]
