# Generated by Django 4.0.4 on 2022-06-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_app', '0009_employees_description_alter_clients_e_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='dog',
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grooming_app.service'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_hour',
            field=models.TimeField(choices=[(1, '8:00'), (1, '9:00'), (1, '10:00'), (1, '11:00'), (1, '12:00'), (1, '13:00'), (1, '14:00'), (1, '15:00'), (1, '16:00'), (1, '17:00'), (1, '18:00')], null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(null=True, verbose_name='Cena'),
        ),
    ]
