# Generated by Django 4.0.4 on 2022-06-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_app', '0010_remove_reservation_end_date_remove_service_dog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start_hour',
            field=models.TimeField(choices=[(1, '8:00'), (2, '9:00'), (3, '10:00'), (4, '11:00'), (5, '12:00'), (6, '13:00'), (7, '14:00'), (8, '15:00'), (9, '16:00'), (10, '17:00'), (11, '18:00')], null=True),
        ),
    ]
