# Generated by Django 4.0.4 on 2022-06-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_app', '0011_alter_reservation_start_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='start_date',
            new_name='start_day',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_hour',
            field=models.TimeField(null=True),
        ),
    ]
