# Generated by Django 4.0.4 on 2022-06-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_app', '0012_rename_start_date_reservation_start_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.TextField(null=True, verbose_name='Opis'),
        ),
    ]
