# Generated by Django 4.0.4 on 2022-06-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_app', '0013_reservation_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='MyReservation',
        ),
    ]
