# Generated by Django 4.0.4 on 2022-06-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_app', '0014_rename_reservation_myreservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myreservation',
            name='dog',
        ),
        migrations.RemoveField(
            model_name='myreservation',
            name='employee',
        ),
    ]
