# Generated by Django 4.0.4 on 2022-06-11 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_app', '0015_remove_myreservation_dog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myreservation',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grooming_app.dogs'),
        ),
    ]
